# Generated by Django 5.2.9 on 2026-01-12 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Healthcare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_health', models.IntegerField(choices=[(1, '非常に悪い'), (2, '悪い'), (3, '普通'), (4, '良い'), (5, '非常に良い')])),
                ('mental_health', models.IntegerField(choices=[(1, '非常に悪い'), (2, '悪い'), (3, '普通'), (4, '良い'), (5, '非常に良い')])),
                ('eat_three_meals', models.BooleanField(default=False)),
                ('exercise_time', models.IntegerField()),
                ('sleep_time', models.IntegerField()),
                ('weight', models.FloatField()),
                ('memo', models.TextField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
