"""
Django settings for mydevproject project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 2026年1月4日変更する　publicにするために、変更した。
import environ


env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")
# # --- 診断開始 ---
# env_path = BASE_DIR / ".env"
# print("\n" + "="*30)
# print(f"1. BASE_DIR の場所: {BASE_DIR}")
# print(f"2. 探しているファイルのフルパス: {env_path}")
# print(f"3. その場所にファイルは存在するか: {env_path.exists()}")

# # ファイルが存在する場合のみ読み込む
# if env_path.exists():
#     environ.Env.read_env(env_path)
#     print("4. 結果: .envファイルを読み込みました")
# else:
#     print("4. 結果: .envファイルが見つからないため、読み込めませんでした")
# print("="*30 + "\n")
# settings.py の修正案
SECRET_KEY = env("DJANGO_SECRET_KEY", default="local-development-only-key")
DEBUG = env.bool("DEBUG", default=True)
# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1"]
)




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'weightapp',
    'weightapp_cbv',
    'accounts.apps.AccountsConfig',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'mydevproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mydevproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    "default": env.db()
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR/"static",]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#2026年1月12日 カスタムを使うことを知らせる。
AUTH_USER_MODEL = 'accounts.CustomUser'

#2026年1月12日
SITE_ID = 1
AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
    # 一般用のメアド認証

    'django.contrib.auth.backends.ModelBackend',
    # 管理用の
)
# 追加した　認証ができなかった
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# メールアドレス認証の設定 古いので新しくなる
# ACCOUNT_AUTHENTICATION_METHOD = 'email'
# ACCOUNT_USERNAME_REQUIRED = False
# サインアップにメールアドレス確認を挟むように設定
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
# ACCOUNT_EMAIL_REQUIRED = True
# 新しい方法
ACCOUNT_LOGIN_METHODS = {"email"}

ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "password1*",
    "password2*",
]




#ログイン　ログアウト後の遷移先の設定
# /menu/ で絶対パスとしたら上手くできた。
LOGIN_REDIRECT_URL = '/menu/'
ACCOUNT_LOGOUT_REDIRECT_URL = 'account_login'

# ワンクリックでログアウト
ACCOUNT_LOGOUT_ON_GET = True

# 確認メールの件名
ACCOUNT_EMAIL_SUBJECT_PREFIX =''

#デフォルトのメール送信元
DEFAULT_FROM_EMAIL = os.environ.get('FROM_EMAIL')